### ISSUE TITLE
Fetching necessary dependencies for the whitelist.

### ISSUE THREAD

**Issue by minhoryang** [adtech-labs/conda-mirror#83]
I'm using conda-mirror for [air-gapped computers](http://docs.anaconda.com/anaconda/user-guide/tasks/install-packages/?#installing-packages-on-a-non-networked-air-gapped-computer). (I know it's a special use case rather than just mirroring.)

Config look like:
```yaml
blacklist:
- name: '*'
platform: osx-64
target_directory: mirrored
upstream_channel: https://repo.continuum.io/pkgs/main/
whitelist:
- build: mkl
  name: _tflow_select
  version: 2.3.0
- build: py36_0
  name: absl-py
  version: 0.7.0
- build: py36_0
  name: astor
  version: 0.7.1
- ...
```

But after `conda-mirror`ing, I can't install whitelisted packages via mirrored, which weren't covered the dependencies.
